#!/usr/bin/env bash
#Installing nginx web server

apt update -y
apt install  nginx -y
ufw enable
ufw allow "Nginx HTTP"
ufw allow "OpenSSH"
echo "Holberton School" > /var/www/html/index.html
service nginx restart
