#!/usr/bin/env bash
#Installing nginx web server

apt-get update -y
apt-get install  nginx -y
ufw enable
ufw allow "Nginx HTTP"
ufw allow "OpenSSH"
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
